### ISSUE TITLE
Default Names For Unmatched

### ISSUE THREAD

**Issue by easton873** [natecraddock/zygrader#14]
I would like to recommend that the default file names for the unmatched student IDs in canvas and zybooks be called ~/unmatchedCanvas.csv and ~/unmatchedZybooks.csv respectively.

**Comment by natecraddock** [comment]
May I propose snake case naming `~/unmatched_canvas.csv` and `~/unmatched_zybooks.csv`

Not at all important :)

**Comment by natecraddock** [comment]
Fixed by 6f5eb3c93f7d6d72b4c3bc1cc1732f5f7d318e0f (missed the `#` in the commit message)
