### ISSUE TITLE
No message for late submitted students

### ISSUE THREAD

**Issue by teiknsmith** [natecraddock/zygrader#23]
When a student has submitted late, there is no message in the grading popup. After picking a submission, there is still no message, but you can view code.

This was found in Fall 2020 on Midterm 1 with late students (ask Riley for names if needed).

**Comment by natecraddock** [comment]
I'll mention that this is probably found in `grader.py`, 'model.py`, or perhaps `zybooks.py` if it deals with the flags on a submission.

If it's in `model.py` then you would want to check the `Submission` class.

**Comment by natecraddock** [comment]
@spencerteiknsmith Is this still an issue? I wasn't able to replicate it on my end. Perhaps sharing some names and lab pairs that raise this issue would be useful. (On discord of course)

---

Wow, I should really read that last sentence above.. Asking Riley then :)

**Comment by natecraddock** [comment]
Closing, the real bug is probably #58
