### ISSUE TITLE
Rename `Back` to `Exit` or `Quit` on the main menu

### ISSUE THREAD

**Issue by natecraddock** [natecraddock/zygrader#27]
This one is low-priority but has bothered me for a long time now. Really, we should make it so you can replace the `Back` string with any arbitrary string.

This will be _much_ nicer to implement after the wm refactor, so I'll spare the details until then. But once that time comes around, this will be easy to do.

This could be done in many places in the source code too,
Preferences could say `Done`
zyBooks section selector could say `Finished`

**Comment by mistBourne1300** [comment]
Let me know when you finish the refactor, I think this would be a good first project for me.

**Comment by natecraddock** [comment]
@mistBourne1300 will do! It should hopefully be next week
