### ISSUE TITLE
Differentiate general-TA Resolvable flags and head-TA specific flags

### ISSUE THREAD

**Issue by derekanderson98** [natecraddock/zygrader#29]
Some flags, such as extensions, can be resolved by any TA, whereas some specifically require review by the head TA. Differentiating the two would help the former category be more reliably handled.

**Comment by teiknsmith** [comment]
We could also make it so that zygrader has to be running in admin mode to clear head-TA specific flags. Maybe we would call them 
`admin-flags` then.

**Comment by derekanderson98** [comment]
That could possibly be a good idea! But at the same time, it would add something that any TA can add that only admin can clear, which would be annoying if you were to somehow accidentally flag something incorrectly, so we might want to consider that repercussion before proceeding with that.

**Comment by teiknsmith** [comment]
As mentioned by Derek in a separate meeting, we could allow the TA who created the admin flag to also clear it (in case they accidentally created it)

**Comment by natecraddock** [comment]
I'm not convinced this is needed.
1. It's been months and I think we have gotten by without this
2. I don't think there are many cases where it is crucial to differentiate _who_ is responsible for resolving the flag. The flag contains a description that usually makes it clear who is responsible.

If you all feel otherwise, feel free to open this again.

**Comment by teiknsmith** [comment]
The idea of quickly seeing if a flag is resolvable is still a good one I think - and your comment on the description actually gave me the following thought:

We could just put the 'resolvability' (see bottom of comment) into the note already stored with the flag. When the `Flag` button is pressed, we could first present a list of options for the resolvability, and then present the text input for the note, and just concatenate the two into the stored note.

If we really want to keep the overhead super low, we could even just modify the text input for the note to remind TAs to please put a resolvability as a prefix to their note. But I think the former option is simple enough and will be more reliable.

I think this will help us still get the benefits of differentiating flags while keeping overhead low.


For the former option we would need a list of 'resolvability' names, and for the latter it would still be good. I can think of two cases right now - "Needs Head TA" and "Waiting on Student" - but there may be other cases. I'd like to discuss what those cases would be with TAs who grade more regularly before calling this list final.

**Comment by natecraddock** [comment]
I think that's a fair solution. And yes, we would need a list of flag categories
