### ISSUE TITLE
Email management feature

### ISSUE THREAD

**Issue by natecraddock** [natecraddock/zygrader#4]
The CS142 TAs share an email account. It's very common to answer emails twice through the shared account, and it may be useful to use zygrader as an email "locker".

The interface would be a new submenu that presents the list of students. Selecting a student would lock it (just like grading). Closing the popup would unlock the student.

One potential issue is matching emails and names. Not all students email from their canvas/zybooks emails. We may need a system to associate additional emails with each student, which would also mean modifying the roster downloader to not overwrite the list of students.

**Comment by teiknsmith** [comment]
The roster downloader wouldn't necessarily need to be modified - alternatively, a new table of `student_identifier -> alternate_email_list` could be built (`student_identifier` could be any number of things [primary email, canvas identifier, BYU ID#, netid, maybe more?])

This could possibly be simpler (although modifying the roster downloader could work and possibly be better overall)
