### ISSUE TITLE
Switching Accounts closes Zygrader

### ISSUE THREAD

**Issue by teiknsmith** [natecraddock/zygrader#52]
When you log out (Preferences > Account > Log Out) and select 'Yes' I would like to sign in with different credentials, zygrader closes anyway.

**Comment by sstanham** [comment]
I can try to fix this problem, can you assign this issue to me?

**Comment by sstanham** [comment]
Thank you for assigning me this issue. I've got zygrader up and running and I was wondering if there is a dummy account I can use to access zyBooks and debug since I am currently a student.

**Comment by natecraddock** [comment]
@sstanham Oh.. how did you find this? I just assumed you were a TA who hadn't yet started dev, not a student at a separate school..

We don't have a test account and cannot give you one because FERPA.
