### ISSUE TITLE
Narrow popups don't show message text

### ISSUE THREAD

**Issue by natecraddock** [natecraddock/zygrader#58]
When the zygrader window is too narrow, the popup message text doesn't display. This might be related to the line wrapping logic.

![image](https://user-images.githubusercontent.com/7967463/98563124-0aea4300-2268-11eb-871a-5e75ae06ca8d.png)

**Comment by teiknsmith** [comment]
I think this might be something I corrected in the mouse-interaction branch forever ago (I went off on a few other features too). I've been working on separating the mouse features from the others right now, and might naturally fix this as I go.
