### ISSUE TITLE
Crash on pressing Enter on empty lists

### ISSUE THREAD

**Issue by traegand** [natecraddock/zygrader#68]
When searching through a list, if you type a character that would produce an empty list on the next refresh and hit the enter key at roughly the same time, zygrader will crash. (My best guess is that it is trying to access an index that existed in the previous list after a refresh has emptied the list)

**Comment by natecraddock** [comment]
Thanks. I think the issue is more simple than timing. If a search returns an empty list then the selected index points to 1, which is not valid in the empty list. We just need to catch this case
