### ISSUE TITLE
Grade Puller Invalid CSV

### ISSUE THREAD

**Issue by easton873** [natecraddock/zygrader#69]
Can't figure out what's going on, but when I pull Ch 9.8-9.10 it creates a bad CSV so I can't put it into the grade book.  I tried it twice and both times it failed.

**Comment by teiknsmith** [comment]
We (Riley and I) redownloaded the canvas_master and it was able to upload afterward.
Unfortunately I forgot to keep the old one to do a proper comparison and definitively identify what caused the issue, but since updating the canvas sheet works we'll close this.
