### ISSUE TITLE
Special characters not read properly

### ISSUE THREAD

**Issue by natecraddock** [natecraddock/zygrader#7]
When entering passwords, some special characters cause zygrader to read the wrong sequence of data.

**Comment by teiknsmith** [comment]
Do you remember which special characters did this? (/is this still an issue with the current version?)

**Comment by natecraddock** [comment]
Not a specific version (though I could find it) but I am fairly certain its still an issue.

And I also do not know the special characters because it was a TAs password. I assume they were interpreted as terminal control characters, so likely some 
`[;]\` characters.

Perhaps we could disable some curses setting when taking masked text input. I consider this semi low priority though

**Comment by natecraddock** [comment]
We don't have a method to replicate this. If it arises again we can create a new issue.
