### ISSUE TITLE
The Grade Puller Misses sometimes, not sure why

### ISSUE THREAD

**Issue by easton873** [natecraddock/zygrader#70]
When I pulled 9.1-9.4 we missed anybody who has a last name between Moss- and the middle of the Peterson bunch.  Not sure what's happening or how I can fix it, but this isn't the first time, a little while ago we missed a bunch in the S's and some of the T's.  I solved the problem by rerunning Zygrader's grade puller.

**Comment by easton873** [comment]
We also missed 7.16-7.18 Sto- to Warn-

**Comment by easton873** [comment]
And 8.1-8.3 last names Kar-Mads

**Comment by natecraddock** [comment]
I'm wondering if perhaps a request doesn't go through, so a portion of the data is missing. A solution could be to only continue execution if the returned list of students matches the number of students we have records for

**Comment by teiknsmith** [comment]
On further discussion with Easton, we are fairly certain this is more to do with Canvas, and a likely solution is just to keep the `canvas_master.csv` up to date.
