### ISSUE TITLE
Authentication timeout gives "Bad Credentials"

### ISSUE THREAD

**Issue by teiknsmith** [natecraddock/zygrader#76]
When authentication times out, an error message of "Bad Credentials" is presented.
I'd bet if the internet is disconnected for some reason, it would probably do the same.
It would be good to present a more specific message so that the cause of the error is more clear.
Or at the least, a more generic message ("Authentication Failure") to be accurate.

**Comment by natecraddock** [comment]
Why the `invalid` label?

**Comment by teiknsmith** [comment]
you know, I did not think about that label referring to the github issue itself as opposed to the behavior of the the code. in regards to the behavior of the code, invalid felt more appropriate than bug. ¯\\\_(ツ)\_/¯

**Comment by natecraddock** [comment]
I figured that was the case :)

And (should have mentioned this above) I agree with the proposal

**Comment by natecraddock** [comment]
I think "Authentication Failure" is a good enough message. If we ever care to catch if there is no internet connection then we can make a new task
