### ISSUE TITLE
No Indication for Empty Parent Rows

### ISSUE THREAD

**Issue by teiknsmith** [natecraddock/zygrader#77]
In ListLayers, parent rows with no children have no indication as such, even when selected. I feel like there should be some indication that "yes, I see that you selected this parent row", even if there are no children.

**Comment by natecraddock** [comment]
What if they were drawn disabled / faded?

**Comment by teiknsmith** [comment]
That would probably work fine if curses has a good attribute for faded text. I'm not sure what other drawing element or style would clearly indicate 'disabled', but if such a method is found then this would make sense.

**Comment by natecraddock** [comment]
We already do this for optional sections in the grade puller. We fade them and make them unclickable

**Comment by teiknsmith** [comment]
that we do. totally forgot about that. that would work great.
