### ISSUE TITLE
Default Excepthook is Not Very Helpful

### ISSUE THREAD

**Issue by teiknsmith** [natecraddock/zygrader#80]
with the new(ish) windowing system, the builtin `sys.excepthook` is not super useful anymore for debugging. it would be far more helpful if it also printed the window stack in addition to the call stack

**Comment by natecraddock** [comment]
I have a decent solution for this unless you have already started work on it (hadn't noticed you claimed it)

**Comment by teiknsmith** [comment]
I hadn't started yet, I'd be interested to see what you have

**Comment by natecraddock** [comment]
![image](https://user-images.githubusercontent.com/7967463/107833646-2e35fa00-6d51-11eb-9740-2e9dcf165d50.png)

I haven't attached it to the exceptions yet, so this is just a hacked-in output, but this is the kind of information I've been able to gather relatively simply

**Comment by natecraddock** [comment]
Here's what I've got so far: https://github.com/natecraddock/zygrader/commit/f1808c5c399d069dceaf157d0dbdaead1bfcea77

branch `fix-80-wm-exceptions`
