### ISSUE TITLE
Use GitHub Releases

### ISSUE THREAD

**Issue by natecraddock** [natecraddock/zygrader#9]
We are tagging (which is great) but we could add an additional workflow step to create a github release (this could be automated from a script like the tagging is). This would allow us to use the api to grab the latest relase, rather than using wget to pipe an installer into python.

**Comment by natecraddock** [comment]
This would be pretty simple. The only downside would be a requirement to make an official GitHub release for each tag.

We could only make an official release for major versions, then rely on the auto-updater to pull in patches. That could work well enough.

Installation would be done with

`python3 -m pip install https://api.github.com/repos/natecraddock/zygrader/releases/latest` rather than the wget script

**Comment by natecraddock** [comment]
We decided this is a good feature. We will edit the push_update.sh script to also push a github release. This will require some auth, but it should be okay.

**Comment by natecraddock** [comment]
Alright, I got too excited here. There isn't an easy way to get the latest release .zip file from github. I can see a couple solutions.
1. Create an install script that automates the commands. I do think it's fun/good for the TAs to get experience running the commands themselves?
2. Perhaps we can use the github actions to automate editing the readme to always insert the correct URL for the latest release in the install notes.

I would prefer option 2. I'll see if it's possible. Perhaps something like https://stackoverflow.com/questions/57921401/push-to-origin-from-github-action

**Comment by teiknsmith** [comment]
If option 2 doesn't take much extra time, I say go for it. This is a once-per-semester issue, so if it adds unneeded work time and complexity, we could just leave it - I like the idea, but it does feel a little complex (but perhaps just as complex as the old install process)

**Comment by natecraddock** [comment]
After thinking about this a lot, I'm just fine to keep our current `hacky` install.

If it becomes an issue, we can just create a bash script to automate the installer and point the TAs to that. Actions is cool, but not exactly the solution to this problem.
