### ISSUE TITLE
Too Many Top-Level Modules

### ISSUE THREAD

**Issue by teiknsmith** [natecraddock/zygrader#93]
in my opinion, we are getting too many top level modules, and we should add a new subpackage to organize better

at first glance, a "menus" package including the following seems to make sense:
- admin.py
- bobs_shake.py
- class_manager.py
- email_manager.py
- grade_puller.py
- grader.py
- user.py
- the `mainloop` function in main.py (perhaps)

some other package structure may exist that makes more sense, I just want to get this idea out while I'm thinking of it

**Comment by natecraddock** [comment]
I think that it wouldn't be a bad thing to do, but at the same time I don't mind keeping the business logic in the root directory of the module, and then other more contained packages for the ui and data. If you want to change it, go for it though.

I would be okay with a menus package

**Comment by teiknsmith** [comment]
looking again I'm not actually that buggered. just while I was working on the tty color fix it looked like a lot. I'm going to close this, changing the file structure wouldn't really be worth the effort
