### ISSUE TITLE
Cluttering `/tmp`

### ISSUE THREAD

**Issue by teiknsmith** [natecraddock/zygrader#94]
zygrader uses `tempfile.mkdtemp`, the docs for which state
> The user of mkdtemp() is responsible for deleting the temporary directory and its contents when done with it."

however, we do not delete the temporary directory

based on observation, I think that the system we run this on cleans up the /tmp folder periodically (I only have ~15 directories there, and zygrader has generated far more dirs than that for me over its lifetime of use)
nevertheless, it would be good if zygrader responsibly cleaned up after itself

**Comment by natecraddock** [comment]
Yeah we definitely could clean up after ourselves. I recall I had some reason why I initially didn't clean up the temp directories, but at the moment I can't think of any issues with it. Some ideas:
* We might be able to use `tempfile.TemporaryDirectory()` so long as the tempdir object remains active throughout the duration of viewing the files in zygrader. It will automatically delete the folder when the object is destroyed.
* Or we can delete the folder when closing the submission(s)
* Another idea (if that doesn't work) would be to keep a list of directories created and then clean them up at exit like we do with locks.
